language: java

jdk: 
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

deploy:
  provider: releases
  api_key:
    secure: XXXXX
  file_glob: true
  file: "build/lib/*.jar"
  skip_cleanup: true
  on:
    repo: repo/path
    tags: true

